force-app/main/default/objects/Product2/fields/Is_Reached_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Is_Reached_Threshold__c</fullName>
    <formula>Quantity__c &lt;= Threshold__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Reached Threshold?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Name__c</fullName>
    <formula>Supplier__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProductHandler.cls
public class ProductHandler {
    
    @AuraEnabled(cacheable = True)
    public static List<Product2> getReorderProducts() {
        return [SELECT Id, Name, Supplier_Name__c, Supplier__c, Quantity__c FROM Product2 Where Is_Reached_Threshold__c = TRUE];
    }

    @AuraEnabled(cacheable = True)
    public static List<Product2> getProducts(){
        return [Select Id, Name, Quantity__c, ProductCode,Supplier__c, Supplier_Name__c  From Product2 Order By Quantity__c];
    }
}